name = "libsvm_reader"
uuid = "84636bd2-d8a4-4ff9-a174-5d03f0c74e61"
authors = ["rcherukuri12 <raja_cherukuri@hotmail.com> and contributors"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
